# Applied Math - Lab 5

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'
import numpy as np

### Saving and Loading numpy array as a readable format
Numpy allows us to save array data into files in a readable manner. We can load these files later on any machine that have numpy installed.

#### Saving a numpy array as a readable file
We can use `np.savetxt(filename:string,X:ndarray)` to save a numpy array `X` to a file named `filename`.  
Example:

In [2]:
Z = np.random.random(10) + np.random.random(10) * 1j

array([0.31120288+0.677519j  , 0.60311855+0.42241218j,
       0.16199529+0.77250865j, 0.79753476+0.60453933j,
       0.57783434+0.45461151j, 0.08848736+0.10813518j,
       0.81334876+0.41045214j, 0.32901186+0.47738241j,
       0.00224421+0.8451449j , 0.98948134+0.64107645j])

In [3]:
np.savetxt('complex_matrix_10x10.txt',Z)

#### Loading a numpy array from a readable file
We can use `np.loadtxt(filename:string)` to create a numpy array from a file saved with `np.savetxt`.  
It assumes the values are of `float` data type.  
If the data type is not float, we should specify the data type in the second parameter.  
Example:

In [4]:
my_old_Z = np.loadtxt('complex_matrix_10x10.txt',np.complex)

array([0.31120288+0.677519j  , 0.60311855+0.42241218j,
       0.16199529+0.77250865j, 0.79753476+0.60453933j,
       0.57783434+0.45461151j, 0.08848736+0.10813518j,
       0.81334876+0.41045214j, 0.32901186+0.47738241j,
       0.00224421+0.8451449j , 0.98948134+0.64107645j])

### Saving and Loading numpy array as a binary format
Numpy allows us to save array data to files in a compact format. We can later load the file in any machine that has numpy installed

#### Saving a numpy array as a binary file
We can use `np.save(filename:string,X:ndarray)` to save a numpy array `X` to a file named `"{filename}.npy"`.  
Example:

In [5]:
A = np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
np.save('cool_matrix_5x5',A)

#### Loading a numpy array from a binary file ( with file extention `.npy`)
We can use `np.load(filename:string)` to create a numpy array from a file saved with `np.save`.  
unlike `np.loadtxt`, this function can get the data type of the array inside the file, making it the best way to save and load array data.  
Example:

In [7]:
my_oldA = np.load('cool_matrix_5x5.npy')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])