# Applied Math - Lab 3

In [33]:
import numpy as np
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

### Reshape a vector
shape of vectors/matrices can be reshaped to other dimensions

In [34]:
vect = np.arange(20)
vect.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
mat = vect.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [38]:
mat.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

### Ravel - flatten a matrix

In [80]:
np.ravel(mat)

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19,  0, 21,  0, 23,  0])

### Combining arrays

In [86]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.concatenate((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [90]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])

np.concatenate((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.concatenate((v1,v2),axis=1)

array([[1, 2, 3, 4, 5, 6]])

### Boolean indexing
We can index arrays with boolean arrays. We can create boolean arrays with boolean operations

In [51]:
mat = np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
mat % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [55]:
mat[mat % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [66]:
mat[mat % 2 == 0] = 0
mat

array([[ 0,  1,  0,  3,  0],
       [ 5,  0,  7,  0,  9],
       [ 0, 11,  0, 13,  0],
       [15,  0, 17,  0, 19],
       [ 0, 21,  0, 23,  0]])

### Getting the indices instead of values

In [101]:
np.argwhere(mat %2 == 1) # not good for indexing

array([[0, 1],
       [0, 3],
       [1, 0],
       [1, 2],
       [1, 4],
       [2, 1],
       [2, 3],
       [3, 0],
       [3, 2],
       [3, 4],
       [4, 1],
       [4, 3]], dtype=int64)

In [104]:
np.where(mat % 2 == 1)

(array([0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4], dtype=int64),
 array([1, 3, 0, 2, 4, 1, 3, 0, 2, 4, 1, 3], dtype=int64))

In [106]:
 mat[np.where(mat%2==1)] # good for indexing

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])